FROM node:20

# Set the working directory
WORKDIR /usr/src/app

# Copiar package.json e instalar dependencias
COPY package*.json ./
RUN npm install --force

# Eliminar bcrypt y reinstalarlo de cero
RUN npm uninstall bcrypt && npm install bcrypt --build-from-source

# Copiar el resto del código de la app
COPY . .

# Generar cliente Prisma
RUN npx prisma generate

# Exponer el puerto de la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "run", "dev"]
