FROM node:20

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies inside Docker
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .
# Expose the port the app runs on
EXPOSE 3000
# Command to run the application
CMD ["npm", "run", "dev"]